version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These arguments are populated from your .env file (formerly envariables)
        # or the shell environment during `docker-compose build`
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_APPWRITE_ENDPOINT: ${NEXT_PUBLIC_APPWRITE_ENDPOINT}
        NEXT_PUBLIC_APPWRITE_PROJECT_ID: ${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
        NEXT_PUBLIC_APPWRITE_BUCKET_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_TRANSACTIONS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_TRANSACTIONS_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_MESSAGES_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_MESSAGES_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_NOTIFICATIONS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_NOTIFICATIONS_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_BOOKMARKS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_BOOKMARKS_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_PROJECTS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_PROJECTS_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_USERS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_USERS_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_JOBS_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_WALLET_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_WALLET_ID}
        NEXT_PUBLIC_APPWRITE_DATABASE_PAYMENTMETHODS_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_PAYMENTMETHODS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_TRANSACTIONS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_TRANSACTIONS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_MESSAGES_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_MESSAGES_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_NOTIFICATIONS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_NOTIFICATIONS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_CATEGORIES_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_CATEGORIES_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_BOOKMARKS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_BOOKMARKS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_PROJECTS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_PROJECTS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_TASKS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_TASKS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILES_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_PROFILES_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_CONNECTIONS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_CONNECTIONS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_APPLICATIONS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_APPLICATIONS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_REVIEWS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_REVIEWS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_JOBS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_JOBS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_CRYPTOTRANSACTIONS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_CRYPTOTRANSACTIONS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_BALANCES_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_BALANCES_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_WALLETS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_WALLETS_ID}
        NEXT_PUBLIC_APPWRITE_COLLECTION_PAYMENTMETHODS_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_PAYMENTMETHODS_ID}
        NEXT_PUBLIC_APPWRITE_BUCKET_MISCELLANEOUS_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_MISCELLANEOUS_ID}
        NEXT_PUBLIC_APPWRITE_BUCKET_MESSAGE_ATTACHMENTS_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_MESSAGE_ATTACHMENTS_ID}
        NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_MEDIA_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_MEDIA_ID}
        NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_DOCUMENTS_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_PROJECT_DOCUMENTS_ID}
        NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_JOB_ATTACHMENTS_ID}
    ports:
      - "3000:3000"
    # env_file can be used for additional runtime variables not prefixed with NEXT_PUBLIC_
    # For NEXT_PUBLIC_ variables, they are baked in at build time.
    # If you have runtime variables in envariables (e.g. API keys not for client), use env_file:
    # env_file:
    #  - ./.env # (formerly envariables)
    restart: unless-stopped

  signaling:
    build:
      context: .
      dockerfile: Dockerfile.signaling
    ports:
      - "4000:4000"
    restart: unless-stopped