name: apps
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  appwrite: ^14.0.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  curved_navigation_bar: ^1.0.6  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web3lancer.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/web3lancer.jpg"
  remove_alpha_ios: true
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/web3lancer.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/web3lancer.jpg"
  linux:
    generate: true
    image_path: "assets/web3lancer.jpg"

flutter_native_splash:
  background_image: "assets/web3lancer.jpg"
  android_12:
    image: assets/web3lancer.jpg